version: '3.7'
services:
  boiler-redis:
    image: redis:2.8.19
    hostname: redis
    container_name: boiler-redis
    expose:
      - "6379"
  sitech-shout:
    image: sitech-shout:latest
    container_name: boiler-celery
    command: [ "celery", "-B" ]
    environment:
      BROKER_URL: redis://redis:6379
